Lynda_MVC_ATM/Controllers/TransactionController.cs
using Lynda_MVC_ATM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace Lynda_MVC_ATM.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Transaction
        public ActionResult Index()
        {
            //List
            IEnumerable<Transaction> transaction = db.transactions.ToList();


            return View(transaction);
        }

        [ActionName("Create")]
        public ActionResult Deopist()
        {
            //获取当前登录用户的ATM Account
            string userId = User.Identity.GetUserId().ToString();

            CheckingAccount checkingAccount = db.checkingAccounts.Where(c => c.AplicationUserID == userId).FirstOrDefault();

            //CheckingAccount 卡号
            string checkingAccountNo = "";
            if (checkingAccount != null)
            {
                checkingAccountNo = checkingAccount.AccountNo;
            }
            ViewBag.currentATMAccountNo = checkingAccountNo;

            //CheckingAccount ID
            int checkingAccountId = 0;
            if (checkingAccount != null)
            {
                checkingAccountId = checkingAccount.id;
            }

            ViewBag.currentATMAccountID = checkingAccountId;

            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Deopist(Transaction entity)
        {
            if (ModelState.IsValid)
            {
                //Save
                db.transactions.Add(entity);
                db.SaveChanges();

                return RedirectToAction("Index", "Home");
            }
            return View(entity);
        }
    }
}

Lynda_MVC_ATM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Middle Valley ATM</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ATM", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("主页", "Index", "Home")</li>
                    <li>@Html.ActionLink("关于", "About", "Home")</li>
                    <li>@Html.ActionLink("交易", "Index", "Transaction")</li>
                    <li>@Html.ActionLink("联系方式", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Middle Valley ATM</p>
            <p>You brower is @Request.Browser.Browser</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>